##### 1. Numpy 使用

> 1. 库的导入

In [37]:
import numpy as np

> 2. 数组的创建 1 （常规）：

In [38]:
a = np.array([1, 2, 3])
b = a.reshape(3, 1) # 三行一列
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f'a :\n{a}\n')
print(f'a.shape = {a.shape}\n')

print(f'b :\n{b}\n')
print(f'b.shape = {b.shape}\n')

print(f'c :\n{c}\n')
print(f'c.shape = {c.shape}\n')


a :
[1 2 3]

a.shape = (3,)

b :
[[1]
 [2]
 [3]]

b.shape = (3, 1)

c :
[[1 2 3 4]
 [5 6 7 8]]

c.shape = (2, 4)



> 3. 数组的创建 2 （特殊数组—全0数组、全1数组、随机数数组等）：

In [39]:
d1 = np.zeros((2, 3))  # 3行4列的全0数组
d2 = np.zeros_like(c)  # 形状和c一样的全0数组
e1 = np.ones((2, 3))   # 2行3列的全1数组
e2 = np.ones_like(c)   # 形状和c一样的全1数组

f = np.random.rand(2, 3)     # 2行3列的均匀分布随机数数组,区间[0,1)
g = np.random.uniform(0, 10, (2, 3)) # [0,10)均匀分布随机数数组,2行3列

h = np.random.randn(2, 3)    # 2行3列的标准正态分布随机数数组
i = np.random.normal(1, 3, (2, 3)) # 均值1，标准差3的正态分布随机数数组,2行3列

j = np.random.randint(0, 10, (2, 3)) # [0,10)均匀分布整数随机数数组,2行3列
k = np.random.random((2, 3))  # 2行3列的均匀抽样分布随机数组,区间[0,1)

In [40]:
# 输出创建的数组
print(f'd1 :\n{d1}\n')
print(f'd1.shape = {d1.shape}\n')

print(f'd2 :\n{d2}\n')
print(f'd2.shape = {d2.shape}\n')

print(f'e1 :\n{e1}\n')
print(f'e1.shape = {e1.shape}\n')

print(f'e2 :\n{e2}\n')
print(f'e2.shape = {e2.shape}\n')

d1 :
[[0. 0. 0.]
 [0. 0. 0.]]

d1.shape = (2, 3)

d2 :
[[0 0 0 0]
 [0 0 0 0]]

d2.shape = (2, 4)

e1 :
[[1. 1. 1.]
 [1. 1. 1.]]

e1.shape = (2, 3)

e2 :
[[1 1 1 1]
 [1 1 1 1]]

e2.shape = (2, 4)



In [41]:
print(f'f :\n{f}\n')
print(f'f.shape = {f.shape}\n')

print(f'g :\n{g}\n')
print(f'g.shape = {g.shape}\n')

print(f'h :\n{h}\n')
print(f'h.shape = {h.shape}\n')

f :
[[0.98243576 0.8446615  0.75672982]
 [0.34715213 0.62550093 0.44269749]]

f.shape = (2, 3)

g :
[[3.28093877 8.40607462 4.45129199]
 [7.85898355 5.956335   7.62158162]]

g.shape = (2, 3)

h :
[[-0.19886053 -0.23361273  1.26393959]
 [-1.30840963 -0.04628892  1.35181499]]

h.shape = (2, 3)



In [42]:
print(f'i :\n{i}\n')
print(f'i.shape = {i.shape}\n')

print(f'j :\n{j}\n')
print(f'j.shape = {j.shape}\n')

print(f'k :\n{k}\n')
print(f'k.shape = {k.shape}\n')

i :
[[ 6.34447682  1.86633422  3.77209302]
 [ 2.37045228 -2.44742166 -1.38414402]]

i.shape = (2, 3)

j :
[[1 6 2]
 [4 9 3]]

j.shape = (2, 3)

k :
[[0.22024057 0.7042564  0.87870698]
 [0.40795351 0.5868781  0.75173741]]

k.shape = (2, 3)



> 4. 数组的创建 3 （由数值范围创建数组）：

In [43]:
l = np.arange(10)        # 0到9的一维数组
m = np.linspace(1, 10, 10) # 等差数列，起点1，终点10，10个数

print(f'l :\n{l}\n')
print(f'l.shape = {l.shape}\n')

print(f'm :\n{m}\n')
print(f'm.shape = {m.shape}\n')

l :
[0 1 2 3 4 5 6 7 8 9]

l.shape = (10,)

m :
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

m.shape = (10,)



> 5. 数据类型： 

![数据类型](../img/1.png)

In [47]:
# 举例
n = np.array([1, 2, 3], dtype=np.int32)  # 指定数据类型为int32
r = np.array([True, False, True], dtype=np.bool_)  # 指定数据类型为布尔型

# 输出
print(f'n :\n{n}\n')
print(f'n.dtype = {n.dtype}\n')

print(f's :\n{s}\n')
print(f's.dtype = {s.dtype}\n')

n :
[1 2 3]

n.dtype = int32

s :
['a' 'b' 'c']

s.dtype = <U1



> 6. 数组属性

![](../img/2.png)

In [50]:
# 举例
n = np.array([1, 2, 3])

#输出
print(f'n.shape :\n{n.shape}\n')

print(f'n.ndim :\n{n.ndim}\n')

n.shape :
(3,)

n.ndim :
1



> 7. 切片（切片切取部分作新数组）：

In [ ]:
sl = slice(2, 7, 2) # 从索引2开始到索引7，步长为2
n = l[sl]