##### 1. Numpy 使用

> 1. 库的导入

In [2]:
import numpy as np

> 2. 数组的创建 1 （常规）：

In [3]:
a = np.array([1, 2, 3])
b = a.reshape(3, 1) # 三行一列
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(f'a :\n{a}\n')
print(f'a.shape = {a.shape}\n')

print(f'b :\n{b}\n')
print(f'b.shape = {b.shape}\n')

print(f'c :\n{c}\n')
print(f'c.shape = {c.shape}\n')


a :
[1 2 3]

a.shape = (3,)

b :
[[1]
 [2]
 [3]]

b.shape = (3, 1)

c :
[[1 2 3 4]
 [5 6 7 8]]

c.shape = (2, 4)



> 3. 数组的创建 2 （特殊数组—全0数组、全1数组、随机数数组等）：

In [4]:
d1 = np.zeros((2, 3))  # 3行4列的全0数组
d2 = np.zeros_like(c)  # 形状和c一样的全0数组
e1 = np.ones((2, 3))   # 2行3列的全1数组
e2 = np.ones_like(c)   # 形状和c一样的全1数组

f = np.random.rand(2, 3)     # 2行3列的均匀分布随机数数组,区间[0,1)
g = np.random.uniform(0, 10, (2, 3)) # [0,10)均匀分布随机数数组,2行3列

h = np.random.randn(2, 3)    # 2行3列的标准正态分布随机数数组
i = np.random.normal(1, 3, (2, 3)) # 均值1，标准差3的正态分布随机数数组,2行3列

j = np.random.randint(0, 10, (2, 3)) # [0,10)均匀分布整数随机数数组,2行3列
k = np.random.random((2, 3))  # 2行3列的均匀抽样分布随机数组,区间[0,1)

In [5]:
# 输出创建的数组
print(f'd1 :\n{d1}\n')
print(f'd1.shape = {d1.shape}\n')

print(f'd2 :\n{d2}\n')
print(f'd2.shape = {d2.shape}\n')

print(f'e1 :\n{e1}\n')
print(f'e1.shape = {e1.shape}\n')

print(f'e2 :\n{e2}\n')
print(f'e2.shape = {e2.shape}\n')

d1 :
[[0. 0. 0.]
 [0. 0. 0.]]

d1.shape = (2, 3)

d2 :
[[0 0 0 0]
 [0 0 0 0]]

d2.shape = (2, 4)

e1 :
[[1. 1. 1.]
 [1. 1. 1.]]

e1.shape = (2, 3)

e2 :
[[1 1 1 1]
 [1 1 1 1]]

e2.shape = (2, 4)



In [6]:
print(f'f :\n{f}\n')
print(f'f.shape = {f.shape}\n')

print(f'g :\n{g}\n')
print(f'g.shape = {g.shape}\n')

print(f'h :\n{h}\n')
print(f'h.shape = {h.shape}\n')

f :
[[0.48458375 0.99655212 0.44470288]
 [0.91681353 0.17130107 0.88111541]]

f.shape = (2, 3)

g :
[[1.15260193 6.19660601 0.47877034]
 [2.01397054 5.7102159  2.79269925]]

g.shape = (2, 3)

h :
[[-0.54116401 -0.73206963 -1.36109537]
 [ 0.14752799  0.7412053  -0.09254828]]

h.shape = (2, 3)



In [7]:
print(f'i :\n{i}\n')
print(f'i.shape = {i.shape}\n')

print(f'j :\n{j}\n')
print(f'j.shape = {j.shape}\n')

print(f'k :\n{k}\n')
print(f'k.shape = {k.shape}\n')

i :
[[ 3.12508549e+00  3.31255728e-03 -2.80782697e-01]
 [ 3.12466417e+00  5.84444909e-01  4.00012293e+00]]

i.shape = (2, 3)

j :
[[0 0 2]
 [7 2 4]]

j.shape = (2, 3)

k :
[[0.7062117  0.98328244 0.13996696]
 [0.75780939 0.91325767 0.04975248]]

k.shape = (2, 3)



> 4. 数组的创建 3 （由数值范围创建数组）：

In [10]:
l = np.arange(10)        # 0到9的一维数组
m = np.linspace(1, 10, 10) # 等差数列，起点1，终点10，10个数

print(f'l :\n{l}\n')
print(f'l.shape = {l.shape}\n')

print(f'm :\n{m}\n')
print(f'm.shape = {m.shape}\n')

l :
[0 1 2 3 4 5 6 7 8 9]

l.shape = (10,)

m :
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

m.shape = (10,)



> 5. 数据类型： 

In [11]:
# 举例
n = np.array([1, 2, 3], dtype=np.int32)  # 指定数据类型为int32
r = np.array([True, False, True], dtype=np.bool_)  # 指定数据类型为布尔型

# 输出
print(f'n :\n{n}\n')
print(f'n.dtype = {n.dtype}\n')

print(f'r :\n{r}\n')
print(f'r.dtype = {r.dtype}\n')

n :
[1 2 3]

n.dtype = int32

r :
[ True False  True]

r.dtype = bool



> 6. 数组属性

In [12]:
# 举例
n = np.array([1, 2, 3])

#输出
print(f'n.shape :\n{n.shape}\n')

print(f'n.ndim :\n{n.ndim}\n')

n.shape :
(3,)

n.ndim :
1



> 7. 切片（切片切取部分作新数组）：

In [18]:
sl = slice(2, 7, 2) # 从索引2开始到索引7，步长为2
n = l[sl]  # l = np.arange(10)  
print(f'sl : {sl}\n')
print(f'n :\n{n}\n')
print(f'n.shape = {n.shape}\n')

sl : slice(2, 7, 2)

n :
[2 4 6]

n.shape = (3,)



> 8. 索引

In [24]:
l = np.arange(10)
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

o1 = l[2:7:2]
o2 = l[2:]

p1 = c[...,  1]  # 第二列
p2 = c[1, ...]  # 第二行
p3 = c[[0, 1], [0, 3]]  # (0,0)和(1,3)位置的元素
p4 = c[c > 5]  # 大于5的元素

print(f'o1 :\n{o1}\n')
print(f'o2 :\n{o2}\n')

print(f'p1 :\n{p1}\n')
print(f'p2 :\n{p2}\n')
print(f'p3 :\n{p3}\n')
print(f'p4 :\n{p4}\n')

o1 :
[2 4 6]

o2 :
[2 3 4 5 6 7 8 9]

p1 :
[2 6]

p2 :
[5 6 7 8]

p3 :
[1 8]

p4 :
[6 7 8]



> 9. 常用函数

In [28]:
l = np.arange(10)

q1 = l.sum()
q2 = l.prod() # 连乘
q3 = l.mean() # 平均值
q4 = l.max()
q5 = l.min()
q6 = l.clip(2, 5) # 限制在2到5之间
q7 = l.var() # 方差
q8 = l.std() # 标准差

print(f'q1 (sum) : {q1}\n')
print(f'q2 (prod) : {q2}\n')
print(f'q3 (mean) : {q3}\n')
print(f'q4 (max) : {q4}\n')
print(f'q5 (min) : {q5}\n')
print(f'q6 (clip 2 to 5) :\n{q6}\n')
print(f'q7 (var) : {q7}\n')
print(f'q8 (std) : {q8}\n')

q1 (sum) : 45

q2 (prod) : 0

q3 (mean) : 4.5

q4 (max) : 9

q5 (min) : 0

q6 (clip 2 to 5) :
[2 2 2 3 4 5 5 5 5 5]

q7 (var) : 8.25

q8 (std) : 2.8722813232690143



##### 2. Pandas使用

> 1. 库的导入：

In [30]:
import pandas as pd

> 2. 序列操作：（series）

In [39]:
# 创建1 （numpy数组创建）

import pandas as pd
import numpy as np

data = np.array(['a', 'b', 'c', 'd'])
s = pd.Series(data)

# 隐式索引
print(s)

# 显式索引
s = pd.Series(data, index=[101, 102, 103, 104])
print(f'\n{s}')

0    a
1    b
2    c
3    d
dtype: object

101    a
102    b
103    c
104    d
dtype: object


In [40]:
# 创建2 （字典创建）

import pandas as pd
import numpy as np

data = {'a': 1, 'b': 2, 'c': 3}
s = pd.Series(data)
print(f'\n{s}')


a    1
b    2
c    3
dtype: int64


In [46]:
# 访问元素

import pandas as pd
s = pd.Series([10, 20, 30, 40, 50], index=['a', 'b', 'c', 'd', 'e'])

print(s)

print(f'\ns[0] : {s[0]}')
print(f's[a] : {s['a']}')

a    10
b    20
c    30
d    40
e    50
dtype: int64

s[0] : 10
s[a] : 10


C:\Users\liu'zhi'gui\AppData\Local\Temp\ipykernel_48552\2513427400.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f'\ns[0] : {s[0]}')


> 3. 数据框操作：（data frame）

In [50]:
# 创建1 （列表创建）

import pandas as pd

data = [1, 2, 3, 4, 5, 6]
df = pd.DataFrame(data)

print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6


In [52]:
# 创建2 (字典嵌套列表创建)

import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Austoin', 'Tom'],
        'Age': [25, 30, 21, 35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Austoin   21
3      Tom   35


In [53]:
# 创建3 （列表嵌套字典）

import pandas as pd

data = [{'a': 1, 'b': 2}, {'a': 3, 'b': 4, 'c': 5}]
df = pd.DataFrame(data)
print(df)

   a  b    c
0  1  2  NaN
1  3  4  5.0


In [58]:
# 创建4 （Series序列创建）

import pandas as pd

data = {'one': pd.Series([1, 2, 3], index=['a', 'b', 'c']),
        'two': pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}
df = pd.DataFrame(data)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [64]:
# 索引1（列索引）
print(df['one'], end='\n\n')

# 索引2（行索引—使用标签）
print(df.loc['b'], end='\n\n')

# 索引3 (行索引-使用整数)
print(df.iloc[2])

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

one    2.0
two    2.0
Name: b, dtype: float64

one    3.0
two    3.0
Name: c, dtype: float64


In [65]:
# 添加数据行(append 方法)

import pandas as pd

df1 = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=['A', 'B'])

df1  =df1.append(df2)
print(df1)

AttributeError: 'DataFrame' object has no attribute 'append'

In [74]:
# 从 Pandas 2.0 版本开始，append 方法被移除。官方推荐使用pandas.concat() 替代它。
import pandas as pd

df1 = pd.DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=['A', 'B'])

df1  =pd.concat([df1, df2])
print(df1)

   A  B
0  1  2
1  3  4
0  5  6
1  7  8


In [75]:
# 删除数据行 (drop)

import pandas as pd

df1 = df1.drop(0)
print(df1)

   A  B
1  3  4
1  7  8


In [77]:
# 数据框属性

import pandas as pd
import numpy as np

d = {'Name': pd.Series(['博客园', 'CSDN', 'Github', '谷歌', '百度', '飞书', 'Bing搜索']),
     'years': pd.Series([2004, 1999, 2008, 1998, 2000, 2016, 2009]),
     'Rating': pd.Series([4.5, 4.0, 4.8, 4.9, 4.2, 4.3, 4.1])}
# 构建 DataFrame
df = pd.DataFrame(d)

#输出 DataFrame的转置
print(df.T)

           0     1       2     3     4     5       6
Name     博客园  CSDN  Github    谷歌    百度    飞书  Bing搜索
years   2004  1999    2008  1998  2000  2016    2009
Rating   4.5   4.0     4.8   4.9   4.2   4.3     4.1


In [2]:
# 描述性统计量

import pandas as pd
import numpy as np

d = {'Name': pd.Series(['小咪', '小美', '小明', '小华', '老刘', '老马', '小王']),
     'Age': pd.Series([25, 26, 34, 28, 50, 48, 36]),
     'Rating': pd.Series([4.5, 4.0, 4.8, 4.9, 4.2, 4.3, 4.1])}
df  = pd.DataFrame(d)

# 按列求平均值
print(df.mean())

# 汇总性描述
print(df.describe())

TypeError: Could not convert ['小咪小美小明小华老刘老马小王'] to numeric

In [4]:
# 描述性统计量

import pandas as pd
import numpy as np

d = {'Name': pd.Series(['小咪', '小美', '小明', '小华', '老刘', '老马', '小王']),
     'Age': pd.Series([25, 26, 34, 28, 50, 48, 36]),
     'Rating': pd.Series([4.5, 4.0, 4.8, 4.9, 4.2, 4.3, 4.1])}
df  = pd.DataFrame(d)

# 按列求平均值
print(df.mean(numeric_only=True))  # 这将只计算Age和Rating列的平均值，忽略“姓名”列

# 方法2
# 选择特定的数字列
# num = ['Age', 'Rating']
# print(df[num].mean())

# 汇总性描述
print(df.describe())

Age       35.285714
Rating     4.400000
dtype: float64
             Age   Rating
count   7.000000  7.00000
mean   35.285714  4.40000
std    10.209706  0.34641
min    25.000000  4.00000
25%    27.000000  4.15000
50%    34.000000  4.30000
75%    42.000000  4.65000
max    50.000000  4.90000


In [6]:
# 排序
import pandas as pd
import numpy as np

uns_df = pd.DataFrame(np.random.randn(10, 2), index=[1, 4, 6, 3, 5, 9, 8, 0, 2, 7], columns=['col1', 'col2'])
sort_df1 = uns_df.sort_index()  # 按标签排序
sort_df2 = uns_df.sort_values(by='col1')  # 按值排序

print(f'原始数据:\n{uns_df}\n')

原始数据:
       col1      col2
1  0.196269  1.117118
4  0.555656 -2.714474
6  0.108443 -0.648287
3  1.172669  1.442093
5  1.542197 -0.220894
9  0.125527 -0.176247
8 -0.892172 -1.057631
0 -0.148719 -0.919061
2 -0.975608  2.272044
7  0.612345 -0.617164



In [10]:
print(f'按标签排序:\n{sort_df1}\n')
print(f'按col1列的值排序:\n{sort_df2}\n')

按标签排序:
       col1      col2
0 -0.148719 -0.919061
1  0.196269  1.117118
2 -0.975608  2.272044
3  1.172669  1.442093
4  0.555656 -2.714474
5  1.542197 -0.220894
6  0.108443 -0.648287
7  0.612345 -0.617164
8 -0.892172 -1.057631
9  0.125527 -0.176247

按col1列的值排序:
       col1      col2
2 -0.975608  2.272044
8 -0.892172 -1.057631
0 -0.148719 -0.919061
6  0.108443 -0.648287
9  0.125527 -0.176247
1  0.196269  1.117118
4  0.555656 -2.714474
7  0.612345 -0.617164
3  1.172669  1.442093
5  1.542197 -0.220894



In [ ]:
# 去重 （drop_duplicates）
import pandas as pd

data = {
    'A': [1, 0, 1, 1],
    'B': [2, 1, 2, 2],
    'C': [3, 4, 3, 3],
    'D': [1, 0, 1, 1],
}
df = pd.DataFrame(data)

print(f'原始数据:\n{df}\n')

df2 = df.drop_duplicates()  # 默认保留第一次出现的重复行
print(f'去重后的数据:\n{df2}\n')

#删除所有重复行
df3 = df.drop_duplicates(keep=False)
print(f'删除所有重复行后的数据:\n{df3}\n')

原始数据:
   A  B  C  D
0  1  2  3  1
1  0  1  4  0
2  1  2  3  1
3  1  2  3  1

去重后的数据:
   A  B  C  D
0  1  2  3  1
1  0  1  4  0

删除所有重复行后的数据:
   A  B  C  D
1  0  1  4  0



In [22]:
# 缺失值处理（NaN）
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['A', 'G', 'E', 'B', 'F'])
df = df.reindex(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
print(f'原始数据:\n{df}')

原始数据:
          0         1         2
A  0.742008 -0.575981 -0.216183
B  1.094452  1.293599 -1.668322
C       NaN       NaN       NaN
D       NaN       NaN       NaN
E  0.228445  1.120467  0.127659
F  1.229789  0.070838 -1.072751
G  1.459015  0.275447 -1.075872
H       NaN       NaN       NaN


In [23]:
# 检查缺失值 （isnull()/notnull）
print(df.isnull())

       0      1      2
A  False  False  False
B  False  False  False
C   True   True   True
D   True   True   True
E  False  False  False
F  False  False  False
G  False  False  False
H   True   True   True


In [25]:
# 填充（替换）缺失值（ fillna()方法 ）
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['A', 'G', 'E', 'B', 'F'])
df = df.reindex(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

print(f'原始数据:\n{df}\n')

df_filled = df.fillna(0)  # 用0填充缺失值
print(f'填充缺失值后的数据:\n{df_filled}\n')

原始数据:
          0         1         2
A -1.132636 -0.099704 -1.144869
B  0.098508 -0.087080 -1.308507
C       NaN       NaN       NaN
D       NaN       NaN       NaN
E -0.072354  0.557967 -0.027621
F -1.178134 -0.765710  0.272358
G -0.446205  0.481777  0.099564
H       NaN       NaN       NaN

填充缺失值后的数据:
          0         1         2
A -1.132636 -0.099704 -1.144869
B  0.098508 -0.087080 -1.308507
C  0.000000  0.000000  0.000000
D  0.000000  0.000000  0.000000
E -0.072354  0.557967 -0.027621
F -1.178134 -0.765710  0.272358
G -0.446205  0.481777  0.099564
H  0.000000  0.000000  0.000000



In [26]:
# 删除缺失值（ dropna()方法 ）
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(5, 3), index=['A', 'G', 'E', 'B', 'F'])
df = df.reindex(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])

print(f'原始数据:\n{df}\n')

df_dropped = df.dropna()  # 删除含有缺失值的行
print(f'删除缺失值后的数据:\n{df_dropped}\n')

原始数据:
          0         1         2
A  0.272652  0.573543 -0.868404
B  1.179051  0.119140 -0.003239
C       NaN       NaN       NaN
D       NaN       NaN       NaN
E  0.252224 -0.424028 -0.745017
F -0.933541 -1.422820  0.321722
G -1.358004  0.885794 -3.128848
H       NaN       NaN       NaN

删除缺失值后的数据:
          0         1         2
A  0.272652  0.573543 -0.868404
B  1.179051  0.119140 -0.003239
E  0.252224 -0.424028 -0.745017
F -0.933541 -1.422820  0.321722
G -1.358004  0.885794 -3.128848

